### ISSUE TITLE
#send results in ReqNotFound

### ISSUE THREAD

**Issue by BradBot1** [violetbuse/httpp#2]
Upon sending a request via httpp I get a "ReqNotFound" error as a response.

I create my request with glibsql and then invoke it via httpp/send#send

I've spent to long trying to figure out why this occurs and am instead reverting to gleam_httpc as that works in this usecase

Here are my deps if you need it

```toml
[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
wisp = ">= 0.16.0 and < 1.0.0"
birl = ">= 1.7.1 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
mist = ">= 1.2.0 and < 2.0.0"
gwt = ">= 0.4.0 and < 1.0.0"
glibsql = ">= 0.7.1 and < 1.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
httpp = ">= 1.1.0 and < 2.0.0"
```
